services:
  web:
    build: .
    command: gunicorn -w 1 -b 0.0.0.0:8000 main:app
    ports:
      - "7479:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: always
    networks:
      - bf_shared_net

networks:
  bf_shared_net:
    external: true